
server:
  error:
    include-message: always
spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: pep
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG